a=int(input('enter a number'))
b=int(input('enter a different number'))
print(f'data type of {a} ; {type(a)}\n data type of {b} ; {type(b)}')
print(f'{a}+{b}={a+b}')
print(f'{a}-{b}={a-b}')
print(f'{a}/{b}={a/b}')
print(f'{a}*{b}={a*b}')
print(f'{a}**{b}={a**b}')
print(f'{a}%{b}={a%b}')